# Generated by Django 4.1.3 on 2022-12-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_linkedin_names', models.JSONField(verbose_name='Array of company linkedin names')),
                ('headcount', models.IntegerField(null=True, verbose_name='Number of people in company')),
                ('known_total_funding', models.IntegerField(null=True, verbose_name='Public valuation')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_li_name', models.CharField(max_length=255, null=True)),
                ('last_title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name of Person')),
            ],
        ),
    ]
