# Generated by Django 4.1.3 on 2022-12-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headcount',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Number of people in company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='known_total_funding',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Public valuation'),
        ),
    ]
