# Generated by Django 4.1.3 on 2022-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpapp', '0002_alter_company_headcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='investors',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Investor List'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_linkedin_names',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Array of company linkedin names'),
        ),
    ]
