# Generated by Django 4.1.3 on 2022-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpapp', '0003_company_investors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_linkedin_names',
        ),
        migrations.AddField(
            model_name='company',
            name='company_linkedin_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Company Linkedin Name'),
        ),
    ]
