# Generated by Django 4.1.3 on 2022-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpapp', '0004_remove_company_company_linkedin_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_linkedin_name',
        ),
        migrations.AddField(
            model_name='company',
            name='company_linkedin_names',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Array of company linkedin names'),
        ),
    ]
